# You can configure your sponsor button by editing a FUNDING.yml file in your repository's
# .github folder, on the default branch. You can configure the button to include sponsored
# developers in GitHub Sponsors, external funding platforms, or a custom funding URL. For
# more information about GitHub Sponsors, see About GitHub Sponsors.
# https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors
#
# You can add one username, package name, or project name per external funding platform
# and up to four custom URLs. You can add one organization and up to four sponsored
# developers in GitHub Sponsors. Add each platform on a new line, using the following
# syntax.

# GitHub Sponsors
# ---
# github: username
# github:
#   - user1
#   - user2
#   - user3
#   - user3

# LFX Mentorship (formerly CommunityBridge)
# ---
# community_bridge: PROJECT-NAME

# IssueHunt
# ---
# issuehunt: USERNAME

# Ko-fi
# ---
# ko_fi: USERNAME

# Liberapay
# ---
# liberapay: USERNAME

# Open Collective
# ---
# open_collective: USERNAME

# Patreon
# ---
# patreon: USERNAME

# Tidelift
#   Tidelift only supports epcific platforms and packages:
#   - npm (JavaScript)
#   - pypi (Python)
#   - rubygems (Ruby)
#   - maven (Java)
#   - packagist (PHP)
#   - nuget (C#)
# ---
# tidelift: PLATFORM-NAME/PACKAGE-NAME

# Polar
# ---
# polar: USERNAME

# Buy Me a Coffee
# ---
# buy_me_a_coffee: USERNAME

# thanks.dev
# ---
# thanks_dev: u/gh/USERNAME

# Custom URL
# custom: LINK1
# custom:
#   - LINK1
#   - LINK2
#   - LINK3
#   - LINK4

github: 'halostatue'
buy_me_a_coffee: 'halostatue'
ko_fi: 'halostatue'
