version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dchook
    main: ./cmd/dchook
    binary: dchook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

  - id: dchook-notify
    main: ./cmd/dchook-notify
    binary: dchook-notify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - id: binaries
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes"
    artifacts: checksum
    output: true

# GitHub artifact attestation
attestations:
  - cmd: gh
    env:
      - GH_TOKEN={{ .Env.GITHUB_TOKEN }}
    args:
      - attestation
      - attest
      - --repo={{ .Env.GITHUB_REPOSITORY }}
      - --predicate-type=https://slsa.dev/provenance/v1
      - --predicate={{ .Env.GITHUB_WORKSPACE }}/dist/metadata.json
      - '${artifact}'
    artifacts: all

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: halostatue
    name: dchook
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
